### ISSUE TITLE
CORS issues still present?

### ISSUE THREAD

**Issue by thilojaeggi** [devgianlu/go-librespot#119]
So I just cloned the latest version and tried to connect to the websocket in my flutter app but keep getting a connection refused error.
This is my config:
```
device_name: nordan
log_level: debug
credentials:
  type: zeroconf
device_type: speaker
server:
  enabled: true
  address: ""
  port: 3678
  allow_origin: "*"
  ```
