### ISSUE TITLE
Initial volume not working as soon as I configure volume_steps

### ISSUE THREAD

**Issue by l3d00m** [devgianlu/go-librespot#131]
I am using the following config on my raspberry 3 on go-librespot version 0.1: 

```yml
device_name: Küche
device_id: XXX
device_type: speaker
credentials:
  type: zeroconf
initial_volume: 60
```

Initial volume works as expected. As soon as I added the following line tho:

```
volume_steps: 20
```

Initial volume stops working, it's always set to 100%.

Maybe related to #32?
