### ISSUE TITLE
API: relative POST player/volume seems to be broken

### ISSUE THREAD

**Issue by 2opremio** [devgianlu/go-librespot#141]
I am using the Alsa mixer with the following configuration:

```yaml
audio_device: default # ALSA audio device to use for playback
mixer_device: default # ALSA mixer device for volume synchronization 
mixer_control_name: Speaker # ALSA mixer control name for volume synchronization
volume_steps: 100 # Volume steps count
initial_volume: 100 # Initial volume in steps (not applied to the mixer device)
external_volume: false # Whether volume is controlled externally 
```

I am also using the  `POST player/volume` endpoint to increase/decrease the volume in a relative manner:

To increase:
```json
{
	"volume": 1,
	"relative": true
}
```

To decrease:
```json
{
	"volume": -1,
	"relative": true
}
```

However,  the volume only increases 1 step up or down (it doesn't continue increasing or decreasing upon multiple API calls).

Also, I get lots of this spurious (and seemly incorrect) warnings:

```
WARN[0015] error while handling alsa mixer events. (Success) 
WARN[0015] error while handling alsa mixer events. (Success) 
WARN[0015] error while handling alsa mixer events. (Success) 
WARN[0015] error while handling alsa mixer events. (Success) 
```
