### ISSUE TITLE
Minimal container based on Alpine Linux

### ISSUE THREAD

**Issue by odiroot** [devgianlu/go-librespot#156]
You might find it useful, if not please just close this issue.

I managed to build a very lightweight container starting with an Alpine Linux 3.20 base. 
The result
```
REPOSITORY                                     TAG                 IMAGE ID      CREATED             SIZE
docker.io/odiroot/go-librespot                 0.1.3               e2413272e241  58 seconds ago      38.7 MB
```
See it published [here](https://hub.docker.com/repository/docker/odiroot/go-librespot/tags/latest/sha256-abc19caba2772f41f50530dee56f9053d4693929fc699debf8a163d7a75491d3). 

Here's the Dockerfile I used
```dockerfile
FROM alpine:3.20 AS build

RUN apk -U --no-cache add \
    git go alsa-lib-dev libogg-dev libvorbis-dev

RUN git clone https://github.com/devgianlu/go-librespot.git

RUN cd go-librespot \
    && go build -v ./cmd/daemon


#####

FROM alpine:3.20

RUN apk -U --no-cache add \
    libpulse avahi libgcc gcompat alsa-lib

COPY --from=build go-librespot/daemon /usr/bin/go-librespot

CMD ["/usr/bin/go-librespot", "--config_dir", "/config"]
```

**Comment by praul** [comment]
Tested it and its working great for me. Thanks, this is more elegant than my own dockerfile.

**Comment by devgianlu** [comment]
Have you used any particular flag to run the container? It is not able to talk to ALSA on my setup.

**Comment by odiroot** [comment]
> Have you used any particular flag to run the container? It is not able to talk to ALSA on my setup.

My bad, only tested with pulse (well, pipewire). 
I could look into the alsa problem.

**Comment by odiroot** [comment]
I also forgot to mention how I run this one.

Minimal compose file would be
```yaml
services:
  go_librespot
    image: docker.io/odiroot/go-librespot:latest
    network_mode: host
    volumes:
      - "./vol_config:/config"
      - "/home/<your username>/.config/pulse/cookie:/pulse_cookie:ro"
      - "/run/user/<your uid>/pulse/native:/pulse_native"
    environment:
      PULSE_SERVER: "unix:/pulse_native"
      PULSE_COOKIE: "/pulse_cookie"
    group_add:
      - keep-groups
    userns_mode: keep-id
```
Naturally `<your username>` has to be replaced with e.g. `whoami` and `<your uid>` with `id -u`.

Now for running with ALSA I believe this should work:
```yaml
services:
  go_librespot
    image: docker.io/odiroot/go-librespot:latest
    network_mode: host
    volumes:
      - "./vol_config:/config"
      - "/usr/share/alsa:/usr/share/alsa:ro"
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - keep-groups
    userns_mode: keep-id
```
