### ISSUE TITLE
Question about spotify_token

### ISSUE THREAD

**Issue by hecht0r** [devgianlu/go-librespot#64]
Hi, 

while using go-librespot with zeroconf works like a charm i want to use stored credentials. With zeroconf i have to select go-librespot as device manually in my spotify client. After that it works perfectly.

I tried to get my access_token via
```
curl -X POST "https://accounts.spotify.com/api/token" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -d "grant_type=client_credentials&client_id=your-client-id&client_secret=your-client-secret"

```
and put it in my config.yml like this:
```
credentials:
  type: spotify_token
  spotify_token:
    username: xxxx@gmail.com     
    access_token:  %he acces_token i got%
```

After starting go-libresport i get error
`FATA[0001] failed running with username and spotify token  error="failed authenticating accesspoint with username and spotify token: failed authenticating: failed login: BadCredentials"` 

What am I doing wrong? Thank you for any help
