### ISSUE TITLE
Possible/sensible to also cache/save ZeroConf credentials?

### ISSUE THREAD

**Issue by felixstorm** [devgianlu/go-librespot#81]
To me it seems like this would open up a simpler option for permanently authenticating especially headless devices externally without having to resort to OAuth2 and to [copying URLs around and using curl](https://github.com/devgianlu/go-librespot/issues/64#issuecomment-2302636971).

Or am I missing something here and this would not make sense or would not work for some reason?

**Comment by devgianlu** [comment]
Should be implemented! You can enable this behaviour with 
```yaml
credentials:
  type: zeroconf
  zeroconf:
    persist_credentials: true
```
